# Builder Stage
FROM golang:1.21.4 as builder

WORKDIR /go/src/app
COPY function.go go.mod go.sum ./

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/function .

# Production Stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/function .

EXPOSE 8081

CMD ["./function"]



