# Builder Stage
FROM golang:1.21.4 as builder

WORKDIR /go/src/app
COPY main.go go.mod go.sum ./

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/main .

# Production Stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]


